/*
 * This source file was generated by the Gradle 'init' task
 */
package businesspermitsystem;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        MainApp classUnderTest = new MainApp();
    }
}
